### ISSUE TITLE
*** Error in `python': double free or corruption (!prev)

### ISSUE THREAD

**Issue by rmldj** [haranjackson/LGMRES#1]
I compiled the library under Python 2 from the Anaconda distribution (nb. had to edit some files in the repository), however sometimes I encounter the following error
```
*** Error in `python': double free or corruption (!prev): 0x00000000029a9290 ***
```
Here is a simple test script which gives me such an error for matrices of size greater than 30:
```
from __future__ import print_function
from numpy import *
import LGMRES

import sys

if len(sys.argv)<2:
    print('Usage: python test.py SIZE')
    quit()

n=int(sys.argv[1])


random.seed(55)

A=random.randn(n,n)
b=random.randn(n)
eps=random.randn(n)

x=linalg.solve(A,b)
print('linalg.solve solution',x,'\n')
x0=x+0.1*eps
print('initial guess',x0,'\n')
x1=LGMRES.solve(A,b,x0=x0)
print('LGMRES.solve solution',x1,'\n')
print('norm of the difference',linalg.norm(x1-x))
```

Did you encounter such an error? Googling around I found one example of such an error in the `pybind11` library but that dealt with strings...

**Comment by haranjackson** [comment]
Hi rmldj, I think you may need to set the option `inner_m` in `LGMRES.solve` to at least `n` in your script above. Does that solve the issue?

**Comment by rmldj** [comment]
Great! It solves it. Thanks!

**Comment by haranjackson** [comment]
Great, no problem!
